### ISSUE TITLE
holyjit

### ISSUE THREAD

**Issue by cztomsik** [Starlight-JS/starlight#11]
https://github.com/nbp/holyjit

The project is dead but you could get some inspiration there. The idea is that you only write interpreter and some wodoo macro will eventually generate very efficient code for that interpreter. But it doesn't have to be interpreted anymore. A bit like JIT JIT compiler.

It's super ambitious but it has been done already - GraalVM compiler is the most successful and production-ready example. TBH, they have far more resources but they also have much bigger scope, so... Definitely possible.

It might be easier to resurrect the project and use it instead of doing JIT all by yourself (and it might be for other dynamic languages implemented in rust).

I would do that myself if I was not busy with other things in my life right now (yeah, I know)

**Comment by playXE** [comment]
Hi! holyjit is nice project but I do not want to implement meta-trace JIT library as it is really hard work because I have to trace either raw assembly or Rust MIR. Instead I will use GCCJIT for optimizing JIT and my own [masm-rs](https://github.com/playxe/masm-rs) library for baseline jit.

UPD:
Meta-tracing also has some disadvantages: 
- It will generate trace for entire interpreter loop rather than for some bytecode sequence
- I can't directly apply optimizations that utilize inline caching when meta-tracing is used
- Performance boost compared to optimizing jit + baseline jit is really small. While baseline JIT can patch code on the fly and optimizing jit can generate code for specific types in specific bytecode sequence meta-tracing JIT can't do all of this. 


If you're interested in meta-tracing JIT in Rust there's [ykrustc](https://github.com/softdevteam/ykrustc) which is a fork of rustc suitable for building meta-tracing JIT.

**Comment by cztomsik** [comment]
Fair point, I guess I just got over-excited :)

BTW: Thanks for the links, I'll definitely have a look.
